export default {
    TWILIO: "twilio",
    ONERING: "onering",
    MYOPERATOR:"myop",
    MISSEDDIAL:"misseddial",
    PHONE_NUMBER_ALREADY_ADDED: "Phone number is already associated with an account",
    ORGANISATION_NAME_EXISTS: "Organisation name already exists.",
    USER_ALREADY_EXISTS: "User already exists",
    USER_NOT_FOUND: "User not found",
    INVALID_ACCOUNT_ID: "Account id is not valid",
    INVALID_DTO: "Dto not valid",
    INVALID_PASSWORD: "Invalid password provided",
    NO_CUSTOMER_IN_QUEUE: "Queue Empty",
    ENV_VAR_NOT_FOUND: "Enviroment variable not defined",
    TOKEN_MISSING: "Token missing",
    JWT_EXPIRED:"jwt expired",
    SLOT_FULL:"Today's slots are full please try booking your slot tomorrow.",
    INVALID_QUEUE_ID: "Queue id not valid",
    APPOINTMENT_DEPARTMENT: "Appointment"
}